# --------- Notes ---------
# If you need to set a block / item, see here for valid values: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Important: Do not use Materials with the 'LEGACY_' prefix
# Intervals are always in game ticks, which means 1 second = 20 game ticks
# When you need to set a distance, it is always in blocks

general:

  # Set how the gui can be opened by using the compass. Possible values are: 'right' (right-click), 'left' (left-click), 'false' (disabled)
  openUsingCompass: right

  teleport:
    # If a teleport to a waypoint was free, should it be counted as a teleportation or not.
    # If it is enabled and in the future you have to pay for the waypoint the prices will go up
    countFreeTeleportations: false

    condition:
      # Specify the minimum time between teleports (if the player has the permission, this will be ignored)
      # Set to 0 to disable the cooldown
      cooldown:
        timeUnit: minutes
        value: 5
      # The amount of seconds a player should be not moving until he can teleport. The timer will start when the player issues the teleport
      # Set to 0 to disable this functionality
      standStillTime: 3
      #
    template: &teleportPayment
      # Available options are 'permissionOnly' (permission is 'waypoints.teleport'), 'pay' (permission and pay) or 'free' (everyone can teleport)
      enabled: permissionOnly
      # What kind of economy should be used for the payment
      # Available options are 'xpPoints', 'xpLevels' and 'vault'. For 'vault' to work you need to have vault installed and setup with a economy
      method: xpPoints
      # You have multiple options that decide how the price will change over time for teleportation
      # 'locked': price = baseAmount
      # The price will always stay at 'baseAmount' disregarding the other values
      # 'linear': price = min(maxAmount, baseAmount + (growthModifier * n))
      # The price will start at 'baseAmount' and will grow with every consecutive teleportation by 'growthModifier' up until 'maxAmount' is reached
      # 'multiply': price = min(maxAmount, baseAmount * (growthModifier ^ n))
      # The price will start at 'baseAmount' and will be multiplied by 'growthModifier' after every use up until 'maxAmount' is reached
      # Numbers with decimals are not permitted except for 'growthModifier' and the result of the equation is always rounded to the nearest full number
      growthType: linear
      baseAmount: 10
      growthModifier: 10
      # Set to -1 to use max value defined by the plugin
      # When using vault the max value is (2 ^ 63) - 1 = 9,223,372,036,854,775,807
      # When using the xp options the max value is ( 2 ^ 31 ) - 1 = 2,147,483,647
      maxAmount: 250

    waypoint:
      death:
        <<: *teleportPayment
      private:
        <<: *teleportPayment
      public:
        <<: *teleportPayment
      permission:
        <<: *teleportPayment

  limits:
    # The maximum amount of waypoints a player can have saved, set to 0 or negative for no limit
    waypoints: 200
    # The maximum amount of folders a player can have saved, set to 0 or negative for no limit
    folders: 50
  # Whether a waypoint should be set, where the player died the last time
  deathWaypointEnabled: true
  # Enable or disable duplicate names here
  allowDuplicateNames:
    waypoints:
      private: true
      public: false
      permission: false
    folders:
      private: true
  allowRenaming:
    # Allow renaming waypoints
    waypoints:
      private: true
      public: true
      permission: true
      # Allow renaming folders
    folders:
      private: true
  customItem:
    # If true players can set custom items for their waypoints and folders
    enabled: true
    filter:
      # How to treat the following list
      # Valid are "blacklist" and "whitelist"
      useAs: blacklist
      # The filter list
      # If set to "blacklist", items in here cannot be used
      # If set to "whitelist", only items in here can be used
      list:
        - AIR
        - BARRIER
        - BEDROCK
  # Translate world names into something more readable
  worldNameAliases:
    # Specify the language here. Examples for other languages: de, at etc.
    en:
      # Here the internal world name is mapped to a readable version
      world: 'Overworld'
      world_nether: 'Nether'
      world_the_end: 'The End'
    de:
      world: 'Welt'
      world_nether: 'Nether'
      world_the_end: 'Das Ende'

inventory:
  general:
    # Maximum line length of descriptions after a linebreak is inserted automatically
    maxDescriptionLineLength: 30
    # Item to go to the previous page
    previousItem: ARROW
    # Item to go to the next page
    nextItem: ARROW
    # Item to go to the previous "window", for example going back from a waypoint to the overview
    backItem: BARRIER
  # Select the items for the yes / no menu
  confirmMenu:
    # The item in the top middle
    descriptionItem: CHEST
    yesItem: GREEN_WOOL
    noItem: RED_WOOL
    backgroundItem: GRAY_STAINED_GLASS_PANE
  overviews:
    # This is the overview that appears when opening the menu without clicking anything
    default:
      backgroundItem: GRAY_STAINED_GLASS_PANE
      # The item that is used to cycle through all the different sort modes
      cycleSortItem: HOPPER
      # The item to deselect the selected waypoints
      deselectItem: MILK_BUCKET
      # The item to toggle the global folders on and off
      toggleGlobalsItem: CHEST
      # The item to click to set a new waypoint
      setWaypointItem: TORCH
      # The item to click to create a new folder
      createFolderItem: WRITABLE_BOOK
    # This is for the folder item for public waypoints
    public:
      item: BOOK
      backgroundItem: GREEN_STAINED_GLASS_PANE
    # This is for the folder item for permission waypoints
    permission:
      item: BOOK
      backgroundItem: RED_STAINED_GLASS_PANE

  # When you want to create a new waypoint via the anvil gui, and have permissions to create more than one type of waypoints,
  # a inventory where you can select the type will be opened
  selectWaypointType:
    backgroundItem: GRAY_STAINED_GLASS_PANE
    # The item acting as the title describing this menu
    titleItem: BOOK
    # The item, which represents a new private waypoint
    privateItem: BEACON
    # The item, which represents a new public waypoint
    publicItem: BEACON
    # The item, which represents a new permission waypoint
    permissionItem: BEACON

  # This is for the window when selecting a folder to move the waypoint into
  selectFolder:
    backgroundItem: GRAY_STAINED_GLASS_PANE
    # The item, when clicked the waypoint is moved back to the overview
    noFolderItem: MAP

  selectBeaconColor:
    backgroundItem: GRAY_STAINED_GLASS_PANE

  # The "item" is the item used as an icon for the waypoint
  # The "selectItem" is the item used to select a waypoint
  # The "teleportItem" is the item used to teleport to a waypoint
  waypoints:
    death:
      item: SKELETON_SKULL
      backgroundItem: GRAY_STAINED_GLASS_PANE
      selectItem: REDSTONE
      teleportItem: ENDER_PEARL
    private:
      # Same as "item", but with the default prefix, because the item can be changed
      defaultItem: BEACON
      backgroundItem: GRAY_STAINED_GLASS_PANE
      selectItem: REDSTONE
      deleteItem: LAVA_BUCKET
      renameItem: NAME_TAG
      # Item to represent the button used to move a waypoint into a folder
      moveToFolderItem: CHEST_MINECART
      teleportItem: ENDER_PEARL
      selectBeaconColorItem: LIME_STAINED_GLASS
    public:
      item: BEACON
      backgroundItem: GREEN_STAINED_GLASS_PANE
      selectItem: REDSTONE
      deleteItem: LAVA_BUCKET
      renameItem: NAME_TAG
      teleportItem: ENDER_PEARL
      selectBeaconColorItem: LIME_STAINED_GLASS
    permission:
      item: BEACON
      backgroundItem: RED_STAINED_GLASS_PANE
      selectItem: REDSTONE
      deleteItem: LAVA_BUCKET
      renameItem: NAME_TAG
      teleportItem: ENDER_PEARL
      selectBeaconColorItem: LIME_STAINED_GLASS
  folders:
    private:
      defaultItem: BOOK
      backgroundItem: GRAY_STAINED_GLASS_PANE
      deleteItem: LAVA_BUCKET
      renameItem: NAME_TAG

displays:
  misc:
    # Set how the displays should only be active when a certain condition is met.
    displaysActiveWhen:
      # Available options are: 'itemInInventory', 'itemInHotbar', 'itemInHand' (main or off-hand), 'false' (disabled)
      enabled: false
      # Only one of the items provided here needs to be present to work, NOT all at once
      requiredItems:
        - COMPASS
        - MAP
        - FILLED_MAP

  wrongWorld:
    # When enabled sends the player a message that he is in the wrong world
    enabled: true
    # When set to true, the message will appear in the action bar, otherwise it is a normal chat message
    actionBar: true
    # The interval in game ticks, in which the message should be sent. If it is set to 0 or lower it will send it only once
    interval: 20

  compass:
    enabled: true

    # When deselecting a waypoint where the compass should point to can be set here
    # Valid values are: 'spawn', 'config', 'previous', 'ingame', 'ingame-lock'
    # If it is set to 'spawn', it will point to the original spawn in the world 'world'
    # If it is set to 'config', it will use the coordinates provided below
    # If it is set to 'previous', the plugin will store the previous compass target and will set it back to that
    # If it is set to 'ingame', you can choose the compass target with /waypoints setcompass
    # If it is set to 'ingame-lock', the location from the command will be used, but it can't be modified
    defaultLocationType: spawn

    defaultLocation:
      world: 'world'
      x: 0
      z: 0

  blinkingBlock:
    enabled: true

    minDistance: 10
    maxDistance: 50

    # The interval in game ticks in which the block should be changed
    interval: 20

    # The blocks that are cycled through
    blocks: [GLASS, GLOWSTONE]

  beacon:
    enabled: true

    minDistance: 50

    # If set to auto it will use the render distance of the server
    maxDistance: auto

    # The base block for the beacon. Use one of these for it to work: IRON_BLOCK, GOLD_BLOCK, DIAMOND_BLOCK or EMERALD_BLOCK
    baseBlock: IRON_BLOCK

    # The interval in game ticks when the ghost block changes should be sent
    interval: 30

    # If set to true, users can select the color of beacon beams for each of their waypoints
    enableSelectColor: true

    defaultColor:
      private: CLEAR
      public: GREEN
      permission: PURPLE
      # The color of the death waypoint cannot be changed by the user
      death: RED

  actionBar:
    # Enable or disable it here
    enabled: true

    interval: 20
    # The indicator color is used to show where the waypoint is by changing the color of one of the sections
    indicatorColor: '&4&l'
    # The background color for the sections
    normalColor: '&7&l'
    # Character (or longer texts, but not recommended) to use as the colored direction indicators
    section: '⬛'
    # If you turn to much to either side these arrows are highlighted to indicator you need tp turn more
    arrow:
      left: '<-'
      right: '->'
    # The amount of sections used to show if you are walking in the correct direction. Must be an odd number or the plugin will correct it by adding one
    amountOfSections: 35
    # The range of between the center section and most outer section in degrees. So the field of view of the action bar indicator is range x 2
    range: 70

  particles:
    enabled: true

    interval: 30

    # The height offset from the ground where the particles should spawn
    heightOffset: 0
    # If set to true, the particles will also point into the direction of the waypoint vertically
    verticalDirection: false
    # The amount of particles
    amount: 10
    # The distance between the particles
    distance: 0.1
    # See here for different particles https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    particle: FLAME
