name: Java CI with Gradle

on:
  push:
    branches: [ "v3/master" ]
  pull_request:
    branches: [ "v3/master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pversion=dev-${{ steps.commit.outputs.short }} :waypoints:shadowJar
      - name: Save produced plugin Jar
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: waypoints/build/libs/waypoints-*.jar
